"""실시간 시세 어댑터 공통 계약."""
from typing import Protocol


class RealtimeAdapter(Protocol):
    def set_on_price(self, callback) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def subscribe(self, symbol: str, market: str = "KRX") -> bool: ...
    async def unsubscribe(self, symbol: str, market: str = "KRX") -> None: ...
    async def listen(self) -> None: ...

    @property
    def subscription_count(self) -> int: ...

    @property
    def is_connected(self) -> bool: ...
